version: '3.8'

services:
  workspace:
    build: .
    container_name: api-distribuicao
    image: api-distribuicao
    restart: always
    tty: true
    stdin_open: true
    environment:
      - TZ=America/Sao_Paulo
